#!/usr/bin/env node
/** Production build — architecture-400 Q1.
 *  Dev stays unbundled (Q2): `python3 -m http.server` on repo root still serves vr/.
 *
 *  Usage: npm run build
 *  Output: dist/vr/ (servable) + dist/shared/
 */

import { cpSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const OUT = join(DIST, 'vr');

rmSync(DIST, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
mkdirSync(join(DIST, 'shared'), { recursive: true });

const result = await esbuild.build({
  entryPoints: [join(ROOT, 'vr/main.js')],
  bundle: true,
  splitting: true,
  format: 'esm',
  outdir: OUT,
  entryNames: 'main-[hash]',
  chunkNames: 'chunk-[name]-[hash]',
  assetNames: 'asset-[name]-[hash]',
  sourcemap: true,
  minify: true,
  target: ['es2022'],
  logLevel: 'info',
  metafile: true,
  // Keep side-effectful CSS / JSON loads working via loaders.
  loader: {
    '.json': 'json',
    '.css': 'css',
    '.woff2': 'file',
    '.png': 'file',
    '.svg': 'file',
  },
});

const outputs = Object.keys(result.metafile.outputs)
  .filter((p) => p.endsWith('.js') && !p.endsWith('.map'))
  .map((p) => relative(ROOT, p));
const mainOut = outputs.find((p) => /main-[A-Z0-9]+\.js$/i.test(p.replace(/\\/g, '/')));
if (!mainOut) {
  console.error('build: could not find hashed main entry in', outputs);
  process.exit(1);
}
const mainRel = './' + mainOut.replace(/^dist\/vr\//, '').replace(/\\/g, '/');

// Static assets the unbundled path still needs beside the entry.
const copies = [
  ['vr/styles', join(OUT, 'styles')],
  ['vr/fonts', join(OUT, 'fonts')],
  ['vr/data', join(OUT, 'data')],
  ['vr/models', join(OUT, 'models')],
  ['vr/vendor', join(OUT, 'vendor')],
  ['shared/tokens.css', join(DIST, 'shared/tokens.css')],
];
for (const [src, dest] of copies) {
  const from = join(ROOT, src);
  if (!existsSync(from)) continue;
  cpSync(from, dest, { recursive: true });
}

let html = readFileSync(join(ROOT, 'vr/index.html'), 'utf8');
html = html.replace(
  /<script type="module" src="\.\/main\.js[^"]*"><\/script>/,
  `<script type="module" src="${mainRel}"></script>`,
);
// tokens path stays ../shared/tokens.css — dist mirrors that.
writeFileSync(join(OUT, 'index.html'), html);

// Also copy marketing site + root redirect so Pages can serve dist/ as the whole product (Q11).
if (existsSync(join(ROOT, 'site'))) {
  cpSync(join(ROOT, 'site'), join(DIST, 'site'), { recursive: true });
}
writeFileSync(join(DIST, '.nojekyll'), '');
writeFileSync(
  join(DIST, 'index.html'),
  `<!DOCTYPE html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=vr/"><link rel="canonical" href="vr/"><title>ORRERY</title><a href="vr/">Open Orrery</a>\n`,
);

// Size report (Q15 seed)
let totalJs = 0;
for (const [file, meta] of Object.entries(result.metafile.outputs)) {
  if (!file.endsWith('.js')) continue;
  totalJs += meta.bytes;
}
const totalKb = (totalJs / 1024).toFixed(1);
writeFileSync(
  join(DIST, 'build-report.json'),
  JSON.stringify(
    {
      updated: new Date().toISOString().slice(0, 10),
      main: mainRel,
      jsBytes: totalJs,
      jsKb: Number(totalKb),
      outputs: outputs.length,
      note: 'architecture-400 Q1 — serve dist/ with any static server; source tree remains the Q2 dev path',
    },
    null,
    2,
  ) + '\n',
);

writeFileSync(
  join(DIST, 'README.md'),
  `# ORRERY build output

Generated by \`npm run build\`. **Do not edit.**

Serve the repo's \`dist/\` root (so \`../shared/tokens.css\` resolves):

\`\`\`bash
npm run build
python3 -m http.server 8766 --directory dist
# http://localhost:8766/vr/
\`\`\`

Dev (Q2) stays unbundled from the source tree — \`python3 -m http.server 8765\` at repo root.

GitHub Pages (Q11) deploys this folder via \`.github/workflows/pages.yml\` (gated on \`npm run verify\`).
`,
);

console.log(`build ok · ${mainRel} · js=${totalKb} KB · chunks=${outputs.length}`);
console.log(`serve: python3 -m http.server 8766 --directory dist`);
