#!/usr/bin/env node
// Compiles vr/data/worlds/columns.json into vr/sim/columnTable.js.
//
//   node scripts/columns.mjs
//
// Layers and recipes are the source of truth. Gates are axes and flags —
// not a body-name regex. The compiler refuses unknown substrates, vary
// keys, or a missing why.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds');
const OUT = join(ROOT, 'vr', 'sim', 'columnTable.js');

const TAGS = new Set(['measured', 'fitted', 'invented']);
const VARY = new Set(['lid', 'ocean']);
const WHEN = new Set(['hpIce', 'clathrate']);
const INTERIORS = new Set(['mobile', 'stagnant', 'episodic', 'heatpipe', 'ice', 'magma', 'fluid']);
const VOLATILES = new Set(['H2O', 'CO2', 'CH4', 'N2', 'SO2', 'H2', 'silicate', 'NH3']);
const NEED_LAYERS = [
  'envelope', 'organics', 'regolith', 'megaregolith',
  'iceLid', 'ocean', 'iceVI', 'clathrate', 'crust',
];
const NEED_RECIPES = [
  'envelope', 'magma', 'iceOrganics', 'iceShell', 'heatpipe', 'airless', 'rocky',
];

const src = JSON.parse(await readFile(join(SRC, 'columns.json'), 'utf8'));
const substrates = JSON.parse(await readFile(join(SRC, 'substrates.json'), 'utf8'));
const layers = src.layers || [];
const recipes = src.recipes || [];
const subIds = new Set((substrates.materials || []).map((m) => m.id));
const problems = [];

const layerIds = new Set();
for (let i = 0; i < layers.length; i++) {
  const L = layers[i];
  if (!L?.id) problems.push(`layer ${i}: missing id`);
  else if (layerIds.has(L.id)) problems.push(`duplicate layer "${L.id}"`);
  else layerIds.add(L.id);
  if (!L?.name) problems.push(`${L?.id || i}: missing name`);
  if (!TAGS.has(L?.tag)) problems.push(`${L?.id || i}: tag "${L?.tag}"`);
  if (!L?.why || L.why.length < 20) problems.push(`${L?.id || i}: why must be a sentence`);
  if (!Array.isArray(L?.rgb) || L.rgb.length !== 3
    || L.rgb.some((c) => !Number.isInteger(c) || c < 0 || c > 255)) {
    problems.push(`${L?.id || i}: rgb must be three integers 0–255`);
  }
  if (L.substrate && !subIds.has(L.substrate)) {
    problems.push(`${L.id}: unknown substrate "${L.substrate}"`);
  }
}

for (const id of NEED_LAYERS) {
  if (!layerIds.has(id)) problems.push(`missing required layer "${id}"`);
}

const recipeIds = new Set();
for (const r of recipes) {
  if (!r?.id) problems.push('recipe missing id');
  else if (recipeIds.has(r.id)) problems.push(`duplicate recipe "${r.id}"`);
  else recipeIds.add(r.id);
  if (!TAGS.has(r?.tag)) problems.push(`${r?.id}: tag "${r?.tag}"`);
  if (!r?.why || r.why.length < 20) problems.push(`${r?.id}: why must be a sentence`);
  if (r.noSurface && r.layers?.length) problems.push(`${r.id}: noSurface recipes must have empty layers`);
  if (!r.noSurface && !Array.isArray(r.layers)) problems.push(`${r.id}: layers must be an array`);
  const n = r.needs || {};
  for (const v of n.interior || []) {
    if (!INTERIORS.has(v)) problems.push(`${r.id}: unknown interior "${v}"`);
  }
  for (const v of n.volatile || []) {
    if (!VOLATILES.has(v)) problems.push(`${r.id}: unknown volatile "${v}"`);
  }
  for (const spec of r.layers || []) {
    if (!layerIds.has(spec.id)) problems.push(`${r.id}: unknown layer "${spec.id}"`);
    if (!(typeof spec.depthKm === 'number' && Number.isFinite(spec.depthKm) && spec.depthKm >= 0)) {
      problems.push(`${r.id}.${spec.id}: depthKm must be ≥ 0`);
    }
    if (spec.vary && !VARY.has(spec.vary)) problems.push(`${r.id}.${spec.id}: unknown vary "${spec.vary}"`);
    if (spec.when && !WHEN.has(spec.when)) problems.push(`${r.id}.${spec.id}: unknown when "${spec.when}"`);
  }
}

for (const id of NEED_RECIPES) {
  if (!recipeIds.has(id)) problems.push(`missing required recipe "${id}"`);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slimLayers = layers.map((L) => ({
  id: L.id,
  name: L.name,
  rgb: L.rgb,
  tag: L.tag,
  why: L.why,
  ...(L.substrate ? { substrate: L.substrate } : {}),
}));

const slimRecipes = recipes.map((r) => ({
  id: r.id,
  tag: r.tag,
  why: r.why,
  ...(r.noSurface ? { noSurface: true } : {}),
  needs: r.needs || {},
  layers: (r.layers || []).map((s) => ({
    id: s.id,
    depthKm: s.depthKm,
    ...(s.vary ? { vary: s.vary } : {}),
    ...(s.when ? { when: s.when } : {}),
  })),
}));

const lines = [];
lines.push('/** GENERATED by scripts/columns.mjs from vr/data/worlds/columns.json — do not edit. */');
lines.push('');
lines.push(`export const COLUMN_VERSION = ${src.version | 0 || 1};`);
lines.push('');
lines.push('/** Named layers a column can contain. */');
lines.push(`export const COLUMN_LAYERS = Object.freeze(${JSON.stringify(slimLayers)}.map((k) => Object.freeze(k)));`);
lines.push('');
lines.push('export const COLUMN_BY_ID = Object.freeze(Object.fromEntries(');
lines.push('  COLUMN_LAYERS.map((k) => [k.id, k]),');
lines.push('));');
lines.push('');
lines.push('/** Recipes, first match wins. Gates are axes and flags. */');
lines.push(`export const COLUMN_RECIPES = Object.freeze(${JSON.stringify(slimRecipes)}.map((k) => Object.freeze(k)));`);
lines.push('');
lines.push('export const RECIPE_BY_ID = Object.freeze(Object.fromEntries(');
lines.push('  COLUMN_RECIPES.map((k) => [k.id, k]),');
lines.push('));');
lines.push('');

await writeFile(OUT, `${lines.join('\n')}\n`);
console.log(`columns: ${layers.length} layers, ${recipes.length} recipes -> ${OUT}`);
