#!/usr/bin/env node
// Compiles vr/data/worlds/cover.json into vr/sim/coverTable.js.
//
//   node scripts/cover.mjs
//
// The JSON is the source of truth. This script validates it — unique ids,
// provenance tags, fine/coarse albedo — and emits a frozen module so the
// browser needs no fetch.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'cover.json');
const OUT = join(ROOT, 'vr', 'sim', 'coverTable.js');

const TAGS = new Set(['measured', 'fitted', 'invented']);
const NEED = ['none', 'frost', 'dust', 'lag', 'tholin', 'sulfur', 'evaporite', 'regolith', 'ray', 'mat', 'biome'];

const src = JSON.parse(await readFile(SRC, 'utf8'));
const kinds = src.kinds || [];
const problems = [];

if (!Array.isArray(kinds) || kinds.length < 8) {
  problems.push(`need at least 8 cover kinds, got ${kinds.length}`);
}

const ids = new Set();
for (let i = 0; i < kinds.length; i++) {
  const k = kinds[i];
  if (!k?.id || typeof k.id !== 'string') problems.push(`slot ${i}: missing id`);
  else if (ids.has(k.id)) problems.push(`duplicate id "${k.id}"`);
  else ids.add(k.id);
  if (!k?.label) problems.push(`${k?.id || i}: missing label`);
  if (!TAGS.has(k?.tag)) problems.push(`${k?.id || i}: tag "${k?.tag}" not measured/fitted/invented`);
  if (!k?.why || k.why.length < 20) problems.push(`${k?.id || i}: why must be a real sentence`);
  if (!Array.isArray(k?.rgb) || k.rgb.length !== 3
    || k.rgb.some((c) => !Number.isInteger(c) || c < 0 || c > 255)) {
    problems.push(`${k?.id || i}: rgb must be three integers 0–255`);
  }
  for (const key of ['albedoFine', 'albedoCoarse']) {
    if (!(typeof k?.[key] === 'number' && Number.isFinite(k[key]))) {
      problems.push(`${k?.id || i}: ${key} must be a finite number`);
    } else if (k[key] < 0 || k[key] > 1) {
      problems.push(`${k?.id || i}: ${key} must be 0–1`);
    }
  }
  if (k.albedoFine < k.albedoCoarse - 1e-6) {
    problems.push(`${k.id}: fine albedo should be ≥ coarse (grain darkens ice/dust)`);
  }
}

for (const id of NEED) {
  if (!ids.has(id)) problems.push(`missing required cover kind "${id}"`);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slim = kinds.map((k) => ({
  id: k.id,
  label: k.label,
  albedoFine: k.albedoFine,
  albedoCoarse: k.albedoCoarse,
  rgb: k.rgb,
  tag: k.tag,
  why: k.why,
  ...(k.cite ? { cite: k.cite } : {}),
}));

const L = [];
L.push('/** GENERATED by scripts/cover.mjs from vr/data/worlds/cover.json — do not edit. */');
L.push('');
L.push(`export const COVER_VERSION = ${src.version | 0 || 1};`);
L.push('');
L.push('/** Cover kinds lying on the substrate. */');
L.push(`export const COVER_KINDS = Object.freeze(${JSON.stringify(slim)}.map((k) => Object.freeze(k)));`);
L.push('');
L.push('export const COVER_BY_ID = Object.freeze(Object.fromEntries(');
L.push('  COVER_KINDS.map((k) => [k.id, k]),');
L.push('));');
L.push('');

await writeFile(OUT, `${L.join('\n')}\n`);
console.log(`cover: ${kinds.length} kinds -> ${OUT}`);
