#!/usr/bin/env node
// Compiles vr/data/worlds/epochs.json into vr/sim/epochTable.js.
//
//   node scripts/epochs.mjs
//
// An epoch is a startable world. The compiler refuses unknown worlds,
// missing why sentences, bad tags, and landscape ids the engine does not have.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'epochs.json');
const OUT = join(ROOT, 'vr', 'sim', 'epochTable.js');

const TAGS = new Set(['measured', 'fitted', 'invented']);
const WORLDS = new Set(['earth', 'venus', 'mars']);
const LAND = new Set([
  'auto', 'pangaea', 'twoworlds', 'shattered', 'archipelago', 'ocean',
  'belt', 'polar', 'dichotomy', 'inland', 'highland', 'ridge', 'crater',
]);
const GAS = new Set(['N2', 'O2', 'CO2', 'CH4', 'H2O', 'dust', 'sulphate']);
const NEED = [
  'present', 'origin', 'cambrian', 'permian', '10ka',
  'hadean', 'archean', 'snowball', 'carboniferous', 'cretaceous', 'lgm',
  'venus-now', 'venus-ocean', 'mars-now', 'mars-wet',
];

const src = JSON.parse(await readFile(SRC, 'utf8'));
const epochs = src.epochs || [];
const problems = [];
const ids = new Set();

if (!Array.isArray(src.worlds) || src.worlds.some((w) => !WORLDS.has(w))) {
  problems.push('worlds must be earth | venus | mars');
}

for (let i = 0; i < epochs.length; i++) {
  const e = epochs[i];
  const at = e?.id || `row ${i}`;
  if (!e?.id) problems.push(`epoch ${i}: missing id`);
  else if (ids.has(e.id)) problems.push(`duplicate epoch "${e.id}"`);
  else ids.add(e.id);
  if (!e?.name) problems.push(`${at}: missing name`);
  if (!WORLDS.has(e?.world)) problems.push(`${at}: world "${e?.world}"`);
  if (!TAGS.has(e?.tag)) problems.push(`${at}: tag "${e?.tag}"`);
  if (!e?.why || e.why.length < 20) problems.push(`${at}: why must be a sentence`);
  if (e.startMaBP != null && !(typeof e.startMaBP === 'number' && Number.isFinite(e.startMaBP) && e.startMaBP >= 0)) {
    problems.push(`${at}: startMaBP must be ≥ 0`);
  }
  if (e.landscape && !LAND.has(e.landscape)) problems.push(`${at}: unknown landscape "${e.landscape}"`);
  if (e.gases) {
    for (const [k, v] of Object.entries(e.gases)) {
      if (!GAS.has(k)) problems.push(`${at}: unknown gas "${k}"`);
      if (!(typeof v === 'number' && v >= 0 && v <= 1)) problems.push(`${at}: ${k} out of range`);
    }
  }
  if (e.oceanRgb) {
    if (!Array.isArray(e.oceanRgb) || e.oceanRgb.length !== 3
      || e.oceanRgb.some((c) => !Number.isInteger(c) || c < 0 || c > 255)) {
      problems.push(`${at}: oceanRgb must be three integers 0–255`);
    }
  }
  if (e.state && e.state !== 'snowball' && e.state !== 'moist-greenhouse') {
    problems.push(`${at}: unknown state "${e.state}"`);
  }
}

for (const id of NEED) {
  if (!ids.has(id)) problems.push(`missing required epoch "${id}"`);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slim = epochs.map((e) => ({
  id: e.id,
  name: e.name,
  world: e.world,
  deepTime: !!e.deepTime,
  startMaBP: e.startMaBP ?? 0,
  tag: e.tag,
  why: e.why,
  tip: e.tip || '',
  ...(e.cite ? { cite: e.cite } : {}),
  ...(e.landscape ? { landscape: e.landscape } : {}),
  ...(e.gases ? { gases: e.gases } : {}),
  ...(e.oceanRgb ? { oceanRgb: e.oceanRgb } : {}),
  ...(e.moonDist != null ? { moonDist: e.moonDist } : {}),
  ...(e.iceBoost != null ? { iceBoost: e.iceBoost } : {}),
  ...(e.iceLat != null ? { iceLat: e.iceLat } : {}),
  ...(e.seaLevelDelta != null ? { seaLevelDelta: e.seaLevelDelta } : {}),
  ...(e.targetLandFrac != null ? { targetLandFrac: e.targetLandFrac } : {}),
  ...(e.moistBoost != null ? { moistBoost: e.moistBoost } : {}),
  ...(e.noGrass ? { noGrass: true } : {}),
  ...(e.state ? { state: e.state } : {}),
  ...(e.unlock ? { unlock: e.unlock } : {}),
}));

const lines = [];
lines.push('/** GENERATED by scripts/epochs.mjs from vr/data/worlds/epochs.json — do not edit. */');
lines.push('');
lines.push(`export const EPOCH_VERSION = ${src.version | 0 || 1};`);
lines.push('');
lines.push(`export const EPOCHS = Object.freeze(${JSON.stringify(slim)}.map((k) => Object.freeze(k)));`);
lines.push('');
lines.push('export const EPOCH_BY_ID = Object.freeze(Object.fromEntries(');
lines.push('  EPOCHS.map((k) => [k.id, k]),');
lines.push('));');
lines.push('');

await writeFile(OUT, `${lines.join('\n')}\n`);
console.log(`epochs: ${epochs.length} rows -> ${OUT}`);
