#!/usr/bin/env node
// CPU fleet contact sheet — one thumbnail per catalogue body from paintDisc.
//
//   node scripts/fleet.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const { CATALOGUE_WORLDS, rulesetFromCatalogue } = await import('../vr/catalogue-rules.js');
const { W, generate } = await import('../vr/world.js');
const { paintDisc, distRgb } = await import('../vr/sim/pictureDisc.js');
const { definitionOf, coverageOfDef } = await import('../vr/sim/definition.js');
const { planetKindWhy } = await import('../vr/sim/planetKind.js');

const cards = [];
let seed = 1;
let twins = 0;
const means = [];

for (const item of CATALOGUE_WORLDS) {
  const rule = rulesetFromCatalogue(item);
  if (!rule) continue;
  generate(seed++, rule);
  const disc = paintDisc(W, 32);
  const rgb = disc.mean.map((n) => n | 0).join(',');
  const def = definitionOf({ rule });
  const cov = coverageOfDef({ rule });
  const { kind, why } = planetKindWhy(rule);
  means.push({ b: item.b, mean: disc.mean, kind });
  cards.push({
    body: item.b,
    cat: item.c || item.t || '',
    kind,
    why: why.slice(0, 40),
    def: def?.id || '—',
    paint: cov.paint || kind,
    rgb,
    filled: disc.filled,
  });
  seed++;
}

for (let i = 0; i < means.length; i++) {
  for (let j = i + 1; j < means.length; j++) {
    if (means[i].kind === means[j].kind) continue;
    if (distRgb(means[i].mean, means[j].mean) < 8) twins++;
  }
}

const grid = cards.map((c) => `
<div class="card" title="${c.body} · ${c.kind} · ${c.def}">
  <i style="background:rgb(${c.rgb})"></i>
  <b>${c.body}</b>
  <small>${c.kind} · ${c.def}</small>
</div>`).join('\n');

const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ORRERY — fleet contact</title>
<style>
:root{ --ground:#0c0f16; --panel:#151a24; --rule:#252d3d; --text:#dbe1ec; --dim:#98a3b7; --faint:#6c7688; --accent:#c69a4f;
  --sans:-apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif; --mono:ui-monospace,Menlo,monospace; }
body{margin:0;background:var(--ground);color:var(--text);font:400 16px/1.55 var(--sans);}
.wrap{max-width:1200px;margin:0 auto;padding:40px 26px 90px;}
h1{font:700 36px/1.05 var(--sans);letter-spacing:-.03em;margin:0;}
.sub{color:var(--dim);max-width:62ch;margin-top:12px;font-size:14.5px;}
.tally{margin:24px 0;color:var(--faint);font:400 12px var(--mono);}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(108px,1fr));gap:8px;}
.card{background:var(--panel);border:1px solid var(--rule);border-radius:8px;padding:8px;text-align:center;}
.card i{display:block;height:32px;border-radius:5px;margin-bottom:6px;border:1px solid var(--rule);}
.card b{display:block;font-size:11.5px;line-height:1.25;}
.card small{display:block;color:var(--faint);font:400 10px var(--mono);margin-top:4px;}
.nav{margin-top:16px;font:400 12.5px var(--mono);color:var(--faint);}
.nav a{color:var(--dim);}
</style>
<div class="wrap">
<h1>Fleet contact</h1>
<p class="sub">CPU orthographic discs from <code>paintDisc</code> — the same colour path as the globe, not a GPU framebuffer. ${cards.length} catalogue bodies. Near-identical unrelated pairs: ${twins} (budget 0).</p>
<p class="nav"><a href="world-data.html">World data</a> · <a href="thrive.html">Thrive</a> · <a href="openworld.html">Backlog</a> · <a href="../vr/">Prototype</a></p>
<p class="tally">Generated by <code>node scripts/fleet.mjs</code></p>
<div class="grid">
${grid}
</div>
</div>
`;

await mkdir(join(ROOT, 'site'), { recursive: true });
await writeFile(join(ROOT, 'site', 'fleet.html'), html);
console.log(`fleet: ${cards.length} bodies, ${twins} near-twin pairs -> site/fleet.html`);
