#!/usr/bin/env node
// Compiles vr/data/worlds/iceshell.json into vr/sim/shellTable.js.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'iceshell.json');
const FORMS = join(ROOT, 'vr', 'data', 'worlds', 'landforms.json');
const OUT = join(ROOT, 'vr', 'sim', 'shellTable.js');

const src = JSON.parse(await readFile(SRC, 'utf8'));
const land = JSON.parse(await readFile(FORMS, 'utf8'));
const formIds = new Set((land.forms || []).map((f) => f.id));
const kinds = src.kinds || [];
const allowedOps = new Set(src.ops || []);
const problems = [];
const ids = new Set();

for (const k of kinds) {
  if (!k?.id) { problems.push('shell kind missing id'); continue; }
  if (ids.has(k.id)) problems.push(`duplicate shell id "${k.id}"`);
  ids.add(k.id);
  for (const f of ['seaLevel', 'ventCap', 'tidalGain']) {
    if (!Number.isFinite(k[f])) problems.push(`${k.id}: ${f} must be finite`);
  }
  for (const id of k.landforms || []) {
    if (!formIds.has(id)) problems.push(`${k.id}: unknown landform "${id}"`);
  }
  for (const op of k.ops || []) {
    if (!op?.type) problems.push(`${k.id}: op missing type`);
    else if (allowedOps.size && !allowedOps.has(op.type)) {
      problems.push(`${k.id}: unknown op "${op.type}"`);
    }
    if (op.form && !formIds.has(op.form)) {
      problems.push(`${k.id}: op form "${op.form}" not in landforms.json`);
    }
  }
}

if (!(src.version >= 3)) problems.push('iceshell: version must be ≥ 3 (mask ops)');

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const L = [];
L.push('/** GENERATED by scripts/iceshell-data.mjs from vr/data/worlds/iceshell.json — do not edit. */');
L.push('');
L.push(`export const SHELL_VERSION = ${src.version | 0 || 1};`);
L.push(`export const SHELL_KINDS = Object.freeze(${JSON.stringify(kinds)}.map((k) => Object.freeze(k)));`);
L.push('export const SHELL_BY_ID = Object.freeze(Object.fromEntries(SHELL_KINDS.map((k) => [k.id, k])));');
L.push('');

await writeFile(OUT, L.join('\n'));
const nOps = kinds.reduce((n, k) => n + (k.ops?.length || 0), 0);
console.log(`iceshell data: ${kinds.length} kinds, ${nOps} ops -> vr/sim/shellTable.js`);
