#!/usr/bin/env node
// Compiles vr/data/worlds/kindRules.json into vr/sim/kindTable.js.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'kindRules.json');
const OUT = join(ROOT, 'vr', 'sim', 'kindTable.js');

const src = JSON.parse(await readFile(SRC, 'utf8'));
const named = src.named || [];
const problems = [];
const kinds = new Set();

for (const r of named) {
  if (!r?.kind) { problems.push('named kind missing kind'); continue; }
  if (!r.re) problems.push(`${r.kind}: missing re`);
  if (r.on !== 'name' && r.on !== 'ident') problems.push(`${r.kind}: on must be name|ident`);
  try { new RegExp(r.re); } catch (e) { problems.push(`${r.kind}: bad re ${e.message}`); }
  if (r.not) {
    try { new RegExp(r.not); } catch (e) { problems.push(`${r.kind}: bad not ${e.message}`); }
  }
  kinds.add(r.kind);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const L = [];
L.push('/** GENERATED by scripts/kindrules.mjs from vr/data/worlds/kindRules.json — do not edit. */');
L.push('');
L.push(`export const KIND_VERSION = ${src.version | 0 || 1};`);
L.push(`export const KIND_NAMED = Object.freeze(${JSON.stringify(named)}.map((k) => Object.freeze(k)));`);
L.push(`export const GAS_KINDS = Object.freeze(new Set(${JSON.stringify(src.gas || [])}));`);
L.push(`export const WHITTAKER_KINDS = Object.freeze(new Set(${JSON.stringify(src.whittaker || [])}));`);
L.push('');
L.push('let compiled = null;');
L.push('function compile() {');
L.push('  if (compiled) return compiled;');
L.push('  compiled = KIND_NAMED.map((r) => ({');
L.push('    kind: r.kind,');
L.push('    on: r.on,');
L.push('    re: new RegExp(r.re),');
L.push('    not: r.not ? new RegExp(r.not) : null,');
L.push('  }));');
L.push('  return compiled;');
L.push('}');
L.push('');
L.push('/** First matching named kind, or null. */');
L.push('export function matchNamedKind(name, ident) {');
L.push('  for (const r of compile()) {');
L.push('    const s = r.on === \'ident\' ? ident : name;');
L.push('    if (r.re.test(s) && (!r.not || !r.not.test(s))) return r.kind;');
L.push('  }');
L.push('  return null;');
L.push('}');
L.push('');

await writeFile(OUT, L.join('\n'));
console.log(`kind rules: ${named.length} named -> vr/sim/kindTable.js`);
