#!/usr/bin/env node
// Compiles vr/data/worlds/processes.json + landforms.json into vr/sim/landGrammar.js.
//
//   node scripts/landgram.mjs
//
// The JSON is the source of truth. Every form's process must exist; substrate
// gates must name a real class or id; tags are measured/fitted/invented.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds');
const OUT = join(ROOT, 'vr', 'sim', 'landGrammar.js');

const TAGS = new Set(['measured', 'fitted', 'invented']);
const HINTS = new Set([
  'crater', 'ridge', 'vent', 'high', 'lava', 'chaos', 'southVent',
  'equator', 'lake', 'soluble', 'polar', 'convect', 'bright', 'flow', 'ice',
]);
const INTERIORS = new Set(['mobile', 'stagnant', 'episodic', 'heatpipe', 'ice', 'magma', 'fluid']);
const VOLATILES = new Set(['H2O', 'CO2', 'CH4', 'N2', 'SO2', 'H2', 'silicate', 'NH3']);
const CLASSES = new Set(['rock', 'ice', 'organics', 'salt', 'metal', 'fluid', 'envelope']);

const read = async (f) => JSON.parse(await readFile(join(SRC, f), 'utf8'));

const processes = (await read('processes.json')).processes || [];
const forms = (await read('landforms.json')).forms || [];
const substrates = (await read('substrates.json')).materials || [];

const problems = [];
const procIds = new Set();
const formIds = new Set();
const subIds = new Set(substrates.map((m) => m.id));
const subClass = new Set(substrates.map((m) => m.class));

if (processes.length < 8) problems.push(`need at least 8 processes, got ${processes.length}`);
if (forms.length < 12) problems.push(`need at least 12 landforms, got ${forms.length}`);

for (const p of processes) {
  if (!p?.id) problems.push('process missing id');
  else if (procIds.has(p.id)) problems.push(`duplicate process "${p.id}"`);
  else procIds.add(p.id);
  if (!p?.name) problems.push(`${p?.id}: missing name`);
  if (!TAGS.has(p?.tag)) problems.push(`${p?.id}: tag "${p?.tag}"`);
  if (!p?.why || p.why.length < 20) problems.push(`${p?.id}: why must be a sentence`);
  if (!(typeof p.rate === 'number' && Number.isFinite(p.rate) && p.rate >= 0)) {
    problems.push(`${p?.id}: rate must be ≥ 0`);
  }
}

for (const f of forms) {
  if (!f?.id) problems.push('form missing id');
  else if (formIds.has(f.id)) problems.push(`duplicate form "${f.id}"`);
  else formIds.add(f.id);
  if (!f?.name) problems.push(`${f?.id}: missing name`);
  if (!procIds.has(f.process)) problems.push(`${f?.id}: unknown process "${f.process}"`);
  if (!TAGS.has(f?.tag)) problems.push(`${f?.id}: tag "${f?.tag}"`);
  if (!f?.why || f.why.length < 20) problems.push(`${f?.id}: why must be a sentence`);
  if (!(f.scaleKm > 0)) problems.push(`${f?.id}: scaleKm must be > 0`);
  if (!(f.reliefM >= 0)) problems.push(`${f?.id}: reliefM must be ≥ 0`);
  if (!Array.isArray(f.rgb) || f.rgb.length !== 3
    || f.rgb.some((c) => !Number.isInteger(c) || c < 0 || c > 255)) {
    problems.push(`${f?.id}: rgb must be three integers 0–255`);
  }
  if (f.hint && !HINTS.has(f.hint)) problems.push(`${f.id}: unknown hint "${f.hint}"`);
  const n = f.needs || {};
  for (const v of n.interior || []) {
    if (!INTERIORS.has(v)) problems.push(`${f.id}: unknown interior "${v}"`);
  }
  for (const v of n.volatile || []) {
    if (!VOLATILES.has(v)) problems.push(`${f.id}: unknown volatile "${v}"`);
  }
  for (const v of n.substrateId || []) {
    if (!subIds.has(v)) problems.push(`${f.id}: unknown substrate "${v}"`);
  }
  for (const v of n.substrateClass || []) {
    if (!CLASSES.has(v) && !subClass.has(v)) {
      problems.push(`${f.id}: unknown substrate class "${v}"`);
    }
  }
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slimP = processes.map((p) => ({
  id: p.id, name: p.name, rate: p.rate, tag: p.tag, why: p.why,
}));
const slimF = forms.map((f) => ({
  id: f.id, name: f.name, process: f.process,
  scaleKm: f.scaleKm, reliefM: f.reliefM, rgb: f.rgb,
  hint: f.hint || null,
  needs: f.needs || {},
  tag: f.tag, why: f.why,
}));

const L = [];
L.push('/** GENERATED by scripts/landgram.mjs from vr/data/worlds/processes.json + landforms.json — do not edit. */');
L.push('');
L.push('export const LANDGRAM_VERSION = 1;');
L.push('');
L.push(`export const PROCESSES = Object.freeze(${JSON.stringify(slimP)}.map((p) => Object.freeze(p)));`);
L.push(`export const LANDFORMS = Object.freeze(${JSON.stringify(slimF)}.map((f) => Object.freeze({ ...f, needs: Object.freeze(f.needs || {}), rgb: Object.freeze(f.rgb) })));`);
L.push('');
L.push('export const PROCESS_BY_ID = Object.freeze(Object.fromEntries(PROCESSES.map((p) => [p.id, p])));');
L.push('export const LANDFORM_BY_ID = Object.freeze(Object.fromEntries(LANDFORMS.map((f) => [f.id, f])));');
L.push('export const LANDFORM_INDEX = Object.freeze(Object.fromEntries(LANDFORMS.map((f, i) => [f.id, i])));');
L.push('');

await writeFile(OUT, `${L.join('\n')}\n`);
console.log(`landgram: ${processes.length} processes, ${forms.length} forms -> ${OUT}`);
