#!/usr/bin/env node
// Compiles the authored life grammar in vr/data/life/*.json into the runtime
// module vr/sim/lifeGrammar.js.
//
//   node scripts/lifegrammar.mjs
//
// The JSON is the source of truth. This script validates it — every organ
// requirement must name an axis option that exists, every organ band must name
// a band that exists — and emits a frozen module so the browser needs no fetch
// and the golden hash stays stable.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'life');
const OUT = join(ROOT, 'vr', 'sim', 'lifeGrammar.js');

const read = async (f) => JSON.parse(await readFile(join(SRC, f), 'utf8'));

const axes = await read('axes.json');
const sensors = await read('sensors.json');
const organs = await read('organs.json');
const biochem = await read('biochem.json');

/* --------------------------------------------------------------- check -- */
const problems = [];
const optionIds = new Map(axes.options.map((a) => [a.id, a.list]));
const intIds = new Map(axes.integers.map((a) => [a.id, a]));
const bandIds = new Set(sensors.bands.map((b) => b.id));
const organIds = new Set(organs.organs.map((o) => o.id));

for (const a of axes.options) {
  if (!a.list.includes(a.ancestral)) problems.push(`axis ${a.id}: ancestral "${a.ancestral}" not in list`);
  if (new Set(a.list).size !== a.list.length) problems.push(`axis ${a.id}: duplicate options`);
}
for (const a of axes.integers) {
  if (a.ancestral < a.min || a.ancestral > a.max) problems.push(`integer ${a.id}: ancestral out of range`);
}
for (const o of organs.organs) {
  if (o.band && o.band !== 'any' && !bandIds.has(o.band)) problems.push(`organ ${o.id}: unknown band "${o.band}"`);
  for (const dep of o.needs?.organs || []) {
    if (!organIds.has(dep)) problems.push(`organ ${o.id}: needs unknown organ "${dep}"`);
  }
  for (const [axis, allowed] of Object.entries(o.needs?.axes || {})) {
    const list = optionIds.get(axis);
    if (!list) { problems.push(`organ ${o.id}: needs unknown axis "${axis}"`); continue; }
    for (const v of allowed) if (!list.includes(v)) problems.push(`organ ${o.id}: axis ${axis} has no option "${v}"`);
  }
  for (const axis of Object.keys(o.needs?.integers || {})) {
    if (!intIds.has(axis)) problems.push(`organ ${o.id}: needs unknown integer axis "${axis}"`);
  }
  if (!['fixed', 'symmetry', 'segments'].includes(o.countFrom)) {
    problems.push(`organ ${o.id}: countFrom "${o.countFrom}" is not fixed | symmetry | segments`);
  }
}
// Organ dependency graph must be acyclic and topologically orderable.
const order = [];
{
  const pending = new Map(organs.organs.map((o) => [o.id, new Set(o.needs?.organs || [])]));
  let guard = 0;
  while (pending.size && guard++ < 500) {
    let moved = false;
    for (const [id, deps] of [...pending]) {
      if ([...deps].every((d) => order.includes(d))) { order.push(id); pending.delete(id); moved = true; }
    }
    if (!moved) break;
  }
  if (pending.size) problems.push(`organ cycle or missing dep: ${[...pending.keys()].join(', ')}`);
}

if (problems.length) {
  console.error('life grammar invalid:');
  for (const p of problems) console.error('  ✗', p);
  process.exitCode = 1;
}

/* ---------------------------------------------------------------- emit -- */
const j = (v) => JSON.stringify(v);
const strip = (o) => {
  const out = {};
  for (const [k, v] of Object.entries(o)) if (!k.startsWith('$')) out[k] = v;
  return out;
};

const L = [];
L.push('/** GENERATED by scripts/lifegrammar.mjs from vr/data/life/*.json — do not edit. */');
L.push('');
L.push(`export const GRAMMAR_VERSION = ${axes.version};`);
L.push('');
L.push('/** Categorical body axes. Index 0 of each list is the ancestral state. */');
L.push(`export const AXES = Object.freeze(${j(axes.options.map(strip))});`);
L.push('');
L.push('/** Counted body axes — integers, not enums, so a body can be pentaradial or 31-segmented. */');
L.push(`export const INTEGERS = Object.freeze(${j(axes.integers.map(strip))});`);
L.push('');
L.push('/** Receptor bands and the physics that decides whether a world can use them. */');
L.push(`export const BANDS = Object.freeze(${j(sensors.bands.map(strip))});`);
L.push(`export const SENSE_CONST = Object.freeze(${j(strip(sensors.constants))});`);
L.push('');
L.push('/** Countable organ modules, topologically ordered by their prerequisites. */');
L.push(`export const ORGANS = Object.freeze(${j(order.map((id) => strip(organs.organs.find((o) => o.id === id))))});`);
L.push('');
L.push('/** Solvent, polymer, energy carrier, handedness, membrane. */');
L.push(`export const BIOCHEM = Object.freeze(${j({
  solvents: biochem.solvents.map(strip),
  polymers: biochem.polymers.map(strip),
  carriers: biochem.carriers.map(strip),
  chirality: biochem.chirality.map(strip),
  membranes: biochem.membranes.map(strip),
})});`);
L.push('');
L.push('export const AXIS = Object.freeze(Object.fromEntries(AXES.map((a, i) => [a.id, i])));');
L.push('export const INT = Object.freeze(Object.fromEntries(INTEGERS.map((a, i) => [a.id, i])));');
L.push('export const ORGAN_BY_ID = Object.freeze(Object.fromEntries(ORGANS.map((o) => [o.id, o])));');
L.push('export const BAND_BY_ID = Object.freeze(Object.fromEntries(BANDS.map((b) => [b.id, b])));');
L.push('');
L.push('/** How many distinct bodies the grammar can name, ignoring organ counts. */');
L.push('export function morphospaceSize() {');
L.push('  let n = 1;');
L.push('  for (const a of AXES) n *= a.list.length;');
L.push('  for (const a of INTEGERS) n *= (a.max - a.min + 1);');
L.push('  return n * Math.pow(2, ORGANS.length);');
L.push('}');
L.push('');

await writeFile(OUT, L.join('\n') + '\n');

const nAxis = axes.options.reduce((n, a) => n * a.list.length, 1);
const nInt = axes.integers.reduce((n, a) => n * (a.max - a.min + 1), 1);
console.log(`life grammar: ${axes.options.length} option axes, ${axes.integers.length} counted axes, ${organs.organs.length} organs, ${sensors.bands.length} bands`);
console.log(`  option combinations   ${nAxis.toExponential(3)}`);
console.log(`  counted combinations  ${nInt.toExponential(3)}`);
console.log(`  organ presence sets   ${Math.pow(2, organs.organs.length).toExponential(3)}`);
console.log(`  morphospace           ${(nAxis * nInt * Math.pow(2, organs.organs.length)).toExponential(3)} distinguishable bodies`);
console.log(problems.length ? `\n${problems.length} problems` : '\nwrote vr/sim/lifeGrammar.js');
