#!/usr/bin/env node
/** Module map — quality-400 N9.
 *  Emits briefs/module-map.md from vr/ headers (first prose comment block).
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const VR = join(ROOT, 'vr');
const OUT = join(ROOT, 'briefs', 'module-map.md');

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (/\.(js|mjs)$/.test(name)) out.push(p);
  }
  return out;
}

function headerBlurb(src) {
  const m = src.match(/^\/\*\*?([\s\S]*?)\*\//);
  if (!m) return '';
  const lines = m[1]
    .split('\n')
    .map((l) => l.replace(/^\s*\*\s?/, '').trim())
    .filter(Boolean)
    .filter((l) => !l.startsWith('@'));
  return (lines[0] || '').slice(0, 120);
}

const files = walk(VR).sort();
const rows = files.map((p) => {
  const rel = relative(ROOT, p).replace(/\\/g, '/');
  let blurb = '';
  try {
    blurb = headerBlurb(readFileSync(p, 'utf8').slice(0, 2000));
  } catch {
    blurb = '';
  }
  return { rel, blurb };
});

const byDir = new Map();
for (const r of rows) {
  const dir = r.rel.includes('/') ? r.rel.slice(0, r.rel.lastIndexOf('/')) : '.';
  if (!byDir.has(dir)) byDir.set(dir, []);
  byDir.get(dir).push(r);
}

let md = `# ORRERY module map

Generated by \`scripts/module-map.mjs\` (${new Date().toISOString().slice(0, 10)}).
**${rows.length}** modules under \`vr/\`. Regenerate after adding files: \`npm run modules:map\`.

| Path | First-line blurb |
|---|---|
`;

for (const [dir, list] of [...byDir.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  md += `\n## \`${dir}/\`\n\n| Path | First-line blurb |\n|---|---|\n`;
  for (const r of list) {
    const name = r.rel.slice(dir.length + 1);
    md += `| [\`${name}\`](../${r.rel}) | ${r.blurb.replace(/\|/g, '\\|')} |\n`;
  }
}

writeFileSync(OUT, md + '\n');
console.log(`module-map · ${rows.length} files → ${relative(ROOT, OUT)}`);
