#!/usr/bin/env node
// Compiles vr/data/worlds/paint.json into vr/sim/paintTable.js.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'paint.json');
const OUT = join(ROOT, 'vr', 'sim', 'paintTable.js');

const src = JSON.parse(await readFile(SRC, 'utf8'));
const problems = [];
const kinds = src.kinds || [];
const squares = src.squares || {};
const ids = new Set();

if (kinds.length < 20) problems.push(`need ≥20 paint kinds, got ${kinds.length}`);
if (Object.keys(squares).length < 30) problems.push('squares table is thin');

for (const k of kinds) {
  if (!k?.id) { problems.push('paint kind missing id'); continue; }
  if (ids.has(k.id)) problems.push(`duplicate paint id "${k.id}"`);
  ids.add(k.id);
  if (k.alias) continue;
  if (!k.const && !k.base && !(k.steps && k.steps.length) && !k.ice) {
    problems.push(`${k.id}: no const, base, steps or ice`);
  }
  if (k.keys) {
    for (const row of k.keys) {
      if (!row.key) problems.push(`${k.id}: key row missing key`);
      else if (!squares[row.key]) problems.push(`${k.id}: unknown square "${row.key}"`);
    }
  }
}

for (const k of kinds) {
  if (k.alias && !ids.has(k.alias) && !kinds.some((x) => x.id === k.alias && !x.alias)) {
    problems.push(`${k.id}: alias "${k.alias}" not found`);
  }
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const resolved = kinds.map((k) => {
  if (!k.alias) return k;
  const srcK = kinds.find((x) => x.id === k.alias && !x.alias);
  return { ...srcK, id: k.id, alias: k.alias };
});

const kindSurface = Object.fromEntries(
  resolved.map((k) => [k.id, k.squares || ['regolith']]),
);

const L = [];
L.push('/** GENERATED by scripts/paint.mjs from vr/data/worlds/paint.json — do not edit. */');
L.push('');
L.push(`export const PAINT_VERSION = ${src.version | 0 || 1};`);
L.push(`export const PAINT = Object.freeze(${JSON.stringify(resolved)}.map((k) => Object.freeze(k)));`);
L.push('export const PAINT_BY_ID = Object.freeze(Object.fromEntries(PAINT.map((k) => [k.id, k])));');
L.push(`export const SQUARES = Object.freeze(${JSON.stringify(squares)});`);
L.push(`export const KIND_SURFACE = Object.freeze(${JSON.stringify(kindSurface)});`);
L.push('');

await writeFile(OUT, L.join('\n'));
console.log(`paint: ${resolved.length} kinds, ${Object.keys(squares).length} squares -> vr/sim/paintTable.js`);
