#!/usr/bin/env node
/** Provenance scanner — earth-fidelity A1–A5, A7, A81.
 *
 *   node scripts/provenance.mjs
 *   node scripts/provenance.mjs --ratchet   # fail if untagged share rises
 *
 * Tag grammar (A2):  /* measured: 5772 K — Sun Teff, IAU 2015 *\/
 * kinds: measured | fitted | invented | numeric | derived | look
 * File header: // @provenance look|invented
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SIM = join(ROOT, 'vr', 'sim');
const OUT = join(ROOT, 'vr', 'data', 'provenance.json');
const BASELINE = join(ROOT, 'vr', 'data', 'provenance-baseline.json');
const LIMITS_GEN = join(ROOT, 'briefs', '_provenance-limits.inc.md');

const KINDS = ['measured', 'fitted', 'invented', 'numeric', 'derived', 'look'];
const TAG_RE = /\/\*\s*(measured|fitted|invented|numeric|derived|look)\s*:[\s\S]*?\*\//gi;
const LINE_TAG_RE = /\/\/\s*(measured|fitted|invented|numeric|derived|look)\s*:/gi;
const PROP_TAG_RE = /\btag\s*:\s*['"](measured|fitted|invented|numeric|derived|look)['"]/gi;
const FILE_TAG_RE = /@provenance\s+(measured|fitted|invented|numeric|derived|look|tagged-module)/i;
const TAGGED_MODULE_RE = /@provenance\s+tagged-module/i;
const CONST_NUM_RE =
  /^(?:export\s+)?const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)/gm;
const NUM_RE = /(?<![\w.$])(-?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)(?![\w.])/g;

/** Generated / look tables — not physics constants (A3/A59). */
const SKIP_FILES =
  /(?:Table|Grammar|Fixtures|catalogue)\.js$|sim\/god\/|substrates\.js$|worldDef\.js$|earthRecord\.js$/;
const GENERATED_HEAD = /GENERATED by scripts\//i;

/** Structural literals that are not physics constants (A4). */
const STRUCTURAL = new Set([
  '0',
  '1',
  '-1',
  '0.5',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '16',
  '24',
  '32',
  '64',
  '96',
  '100',
  '255',
  '256',
  '512',
  '0.0',
  '1.0',
  '2.0',
  '0.25',
  '0.75',
  '1.5',
  '0.1',
  '0.01',
  '0.001',
]);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name.endsWith('.map')) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (/\.(js|mjs)$/.test(name)) out.push(p);
  }
  return out;
}

function stripStringsAndComments(src) {
  // Keep block tags for counting, but remove strings so numbers in strings don't count.
  return src
    .replace(/`(?:\\.|[^`\\])*`/g, '""')
    .replace(/'(?:\\.|[^'\\])*'/g, '""')
    .replace(/"(?:\\.|[^"\\])*"/g, '""');
}

function lineHasTag(lines, idx) {
  for (let i = Math.max(0, idx - 2); i <= idx; i++) {
    const L = lines[i];
    if (TAG_RE.test(L) || LINE_TAG_RE.test(L)) {
      TAG_RE.lastIndex = 0;
      LINE_TAG_RE.lastIndex = 0;
      return true;
    }
  }
  return false;
}

function analyzeTaggedModule(rel, src, linesCount) {
  const lines = src.split('\n');
  const kinds = {};
  const tags = [
    ...src.matchAll(TAG_RE),
    ...src.matchAll(LINE_TAG_RE),
    ...src.matchAll(PROP_TAG_RE),
  ].map((m) => m[1].toLowerCase());
  for (const k of tags) kinds[k] = (kinds[k] || 0) + 1;

  let physics = 0;
  let taggedConsts = 0;
  let untagged = 0;
  const missing = [];
  for (const m of src.matchAll(CONST_NUM_RE)) {
    const name = m[1];
    const lit = m[2];
    // Named module consts always count — even small ints (nPlates, etc.).
    if (STRUCTURAL.has(lit) && !/^[A-Z]/.test(name)) continue;
    physics++;
    const before = src.slice(0, m.index);
    const lineIdx = before.split('\n').length - 1;
    if (lineHasTag(lines, lineIdx)) taggedConsts++;
    else {
      untagged++;
      missing.push(name);
    }
  }
  return {
    file: rel,
    lines: linesCount,
    fileTag: 'tagged-module',
    tagged: taggedConsts,
    untagged,
    physics,
    structural: 0,
    kinds,
    skip: false,
    density: linesCount ? (untagged / linesCount) * 100 : 0,
    missing,
  };
}

function analyzeFile(path, src) {
  const rel = relative(ROOT, path).replace(/\\/g, '/');
  const fileTag = (src.match(FILE_TAG_RE) || [])[1]?.toLowerCase() || null;
  const lines = src.split('\n').length;

  if (TAGGED_MODULE_RE.test(src)) {
    return analyzeTaggedModule(rel, src, lines);
  }

  // File-level look/invented cosmetic modules drop out of physics denominator (A3).
  if (
    fileTag === 'look' ||
    (fileTag === 'invented' && /sim\/god\//.test(rel)) ||
    SKIP_FILES.test(rel) ||
    GENERATED_HEAD.test(src.slice(0, 240))
  ) {
    return {
      file: rel,
      lines,
      fileTag: fileTag || 'look',
      tagged: 0,
      untagged: 0,
      physics: 0,
      kinds: {},
      skip: true,
      reason: fileTag ? `file-tag ${fileTag}` : 'generated/look table',
    };
  }

  const tags = [
    ...src.matchAll(TAG_RE),
    ...src.matchAll(LINE_TAG_RE),
    ...src.matchAll(PROP_TAG_RE),
  ].map((m) => m[1].toLowerCase());
  const kinds = {};
  for (const k of tags) kinds[k] = (kinds[k] || 0) + 1;

  const stripped = stripStringsAndComments(src)
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/\/\/.*$/gm, ' ');

  let physics = 0;
  let structural = 0;
  for (const m of stripped.matchAll(NUM_RE)) {
    const lit = m[1];
    if (STRUCTURAL.has(lit)) {
      structural++;
      continue;
    }
    // Integer indices / small counters
    if (/^-?\d+$/.test(lit)) {
      const n = Math.abs(parseInt(lit, 10));
      if (n <= 64) {
        structural++;
        continue;
      }
    }
    physics++;
  }

  const tagged = tags.length;
  // Untagged physics estimate: physics literals not adjacent to a tag.
  // Conservative: untagged = max(0, physics - tagged).
  const untagged = Math.max(0, physics - tagged);

  return {
    file: rel,
    lines,
    fileTag,
    tagged,
    untagged,
    physics,
    structural,
    kinds,
    skip: false,
    density: lines ? (untagged / lines) * 100 : 0,
  };
}

function scan() {
  const files = walk(SIM);
  // A8 — rulesets + dials module sit outside sim/
  for (const extra of [
    join(ROOT, 'vr', 'rulesets.js'),
    join(ROOT, 'vr', 'sim', 'terraParams.js'),
  ]) {
    try {
      if (statSync(extra).isFile() && !files.includes(extra)) files.push(extra);
    } catch {
      /* */
    }
  }
  const rows = files.map((p) => analyzeFile(p, readFileSync(p, 'utf8')));
  const active = rows.filter((r) => !r.skip);
  let tagged = 0,
    untagged = 0,
    physics = 0;
  const kinds = Object.fromEntries(KINDS.map((k) => [k, 0]));
  for (const r of active) {
    tagged += r.tagged;
    untagged += r.untagged;
    physics += r.physics;
    for (const [k, v] of Object.entries(r.kinds)) kinds[k] = (kinds[k] || 0) + v;
  }
  const denom = tagged + untagged;
  const untaggedShare = denom ? untagged / denom : 0;
  return {
    generated: new Date().toISOString(),
    kinds,
    tagged,
    untagged,
    physics,
    denom,
    untaggedShare,
    files: rows,
    topUntagged: active
      .slice()
      .sort((a, b) => b.density - a.density)
      .slice(0, 10)
      .map((r) => ({
        file: r.file,
        density: +r.density.toFixed(2),
        untagged: r.untagged,
        tagged: r.tagged,
      })),
  };
}

function printTable(report) {
  console.log('provenance scanner');
  console.log(
    `  tagged ${report.tagged} · untagged ${report.untagged} · physics~${report.physics}`,
  );
  console.log(
    `  untagged share ${(report.untaggedShare * 100).toFixed(1)}%  (denom ${report.denom})`,
  );
  console.log('  kinds:', KINDS.map((k) => `${k}=${report.kinds[k] || 0}`).join(' '));
  console.log('\n  densest untagged (per 100 lines):');
  for (const t of report.topUntagged) {
    console.log(`    ${String(t.density).padStart(6)}  ${t.file}  (u${t.untagged}/t${t.tagged})`);
  }
}

function writeProvenance(report) {
  mkdirSync(dirname(OUT), { recursive: true });
  const slim = {
    generated: report.generated,
    tagged: report.tagged,
    untagged: report.untagged,
    physics: report.physics,
    denom: report.denom,
    untaggedShare: report.untaggedShare,
    kinds: report.kinds,
    topUntagged: report.topUntagged,
    history: [],
  };
  try {
    const prev = JSON.parse(readFileSync(OUT, 'utf8'));
    if (Array.isArray(prev.history)) slim.history = prev.history.slice(-40);
  } catch {
    /* first run */
  }
  slim.history.push({
    at: report.generated,
    untaggedShare: report.untaggedShare,
    tagged: report.tagged,
    untagged: report.untagged,
  });
  writeFileSync(OUT, JSON.stringify(slim, null, 2) + '\n');
  console.log(`\nwrote ${relative(ROOT, OUT)}`);
}

function writeLimitsInc(report) {
  const md = `<!-- generated by scripts/provenance.mjs — do not hand-edit -->
### Provenance ratio (generated)

As of **${report.generated.slice(0, 10)}**: **${report.tagged}** tagged · **${report.untagged}** untagged
physics-ish literals under \`vr/sim/\` (structural 0/1/2… excluded). Untagged share
**${(report.untaggedShare * 100).toFixed(1)}%**. Kinds: ${KINDS.map((k) => `${k} ${report.kinds[k] || 0}`).join(', ')}.

Rule: untagged means invented until proven otherwise. Ratchet: \`node scripts/provenance.mjs --ratchet\`.
`;
  writeFileSync(LIMITS_GEN, md);
  console.log(`wrote ${relative(ROOT, LIMITS_GEN)}`);
}

function ratchet(report) {
  let base;
  try {
    base = JSON.parse(readFileSync(BASELINE, 'utf8'));
  } catch {
    writeFileSync(
      BASELINE,
      JSON.stringify(
        {
          committed: report.generated,
          untaggedShare: report.untaggedShare,
          tagged: report.tagged,
          untagged: report.untagged,
          note: 'First baseline — ratchet fails only when share rises above this',
        },
        null,
        2,
      ) + '\n',
    );
    console.log(`committed baseline → ${relative(ROOT, BASELINE)}`);
    return true;
  }
  const eps = 1e-4;
  if (report.untaggedShare > base.untaggedShare + eps) {
    console.error(
      `RATCHET FAIL: untagged share ${(report.untaggedShare * 100).toFixed(2)}% > baseline ${(base.untaggedShare * 100).toFixed(2)}%`,
    );
    return false;
  }
  console.log(`ratchet ok (≤ ${(base.untaggedShare * 100).toFixed(2)}%)`);
  return true;
}

const HOTSPOTS = [
  'vr/sim/terraParams.js',
  'vr/sim/atmo.js',
  'vr/sim/hydro.js',
  'vr/sim/carbon.js',
  'vr/sim/evolve.js',
];

function assertHotspots(report) {
  let ok = true;
  console.log('\nhotspots (A8–A13):');
  for (const id of HOTSPOTS) {
    const row = report.files.find((f) => f.file === id);
    if (!row) {
      console.error(`  FAIL  ${id} — not scanned`);
      ok = false;
      continue;
    }
    if (row.fileTag !== 'tagged-module') {
      console.error(`  FAIL  ${id} — missing @provenance tagged-module`);
      ok = false;
      continue;
    }
    if (row.untagged > 0) {
      console.error(
        `  FAIL  ${id} — ${row.untagged} untagged consts: ${(row.missing || []).join(', ')}`,
      );
      ok = false;
      continue;
    }
    if (row.physics < 1) {
      console.error(`  FAIL  ${id} — no physics consts found`);
      ok = false;
      continue;
    }
    console.log(`  PASS  ${id} · ${row.tagged}/${row.physics} tagged`);
  }
  // A12 — every GUILDS entry carries a tag
  try {
    const redoxSrc = readFileSync(join(ROOT, 'vr/sim/redox.js'), 'utf8');
    const guildTags = [
      ...redoxSrc.matchAll(/id:\s*'[^']+'[\s\S]*?tag:\s*'(measured|fitted|invented)'/g),
    ];
    const guildIds = [...redoxSrc.matchAll(/\{\s*id:\s*'([^']+)'/g)];
    if (guildIds.length < 10 || guildTags.length < guildIds.length) {
      console.error(
        `  FAIL  vr/sim/redox.js GUILDS — ${guildTags.length}/${guildIds.length} tagged`,
      );
      ok = false;
    } else {
      console.log(`  PASS  vr/sim/redox.js GUILDS · ${guildTags.length}/${guildIds.length} tagged`);
    }
  } catch (e) {
    console.error('  FAIL  redox guild check', e.message);
    ok = false;
  }
  const rs = report.files.find((f) => f.file === 'vr/rulesets.js');
  if (rs && !rs.skip && rs.fileTag !== 'look') {
    console.error('  FAIL  vr/rulesets.js should be @provenance look (dials in terraParams)');
    ok = false;
  } else {
    console.log('  PASS  vr/rulesets.js · look (dials → terraParams)');
  }
  return ok;
}

const report = scan();
printTable(report);
writeProvenance(report);
writeLimitsInc(report);

const wantRatchet = process.argv.includes('--ratchet');
const wantHotspots = process.argv.includes('--hotspots') || wantRatchet;
if (wantHotspots && !assertHotspots(report)) process.exitCode = 1;
if (wantRatchet && !ratchet(report)) process.exitCode = 1;
else if (!wantRatchet && !wantHotspots) {
  try {
    readFileSync(BASELINE);
  } catch {
    ratchet(report);
  }
}
