#!/usr/bin/env node
// Compiles vr/data/worlds/stamps.json into vr/sim/stampTable.js.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'stamps.json');
const FORMS = join(ROOT, 'vr', 'data', 'worlds', 'landforms.json');
const OUT = join(ROOT, 'vr', 'sim', 'stampTable.js');

const src = JSON.parse(await readFile(SRC, 'utf8'));
const land = JSON.parse(await readFile(FORMS, 'utf8'));
const formIds = new Set((land.forms || []).map((f) => f.id));
const kinds = src.kinds || [];
const allowedOps = new Set(src.ops || []);
const problems = [];
const ids = new Set();

for (const k of kinds) {
  if (!k?.id) { problems.push('stamp kind missing id'); continue; }
  if (ids.has(k.id)) problems.push(`duplicate stamp id "${k.id}"`);
  ids.add(k.id);
  if (k.craters) {
    for (const f of ['nLarge', 'nMid', 'depth', 'micro']) {
      if (!Number.isFinite(k.craters[f])) problems.push(`${k.id}: craters.${f} must be finite`);
    }
  }
  if (k.extraCraters && !Number.isFinite(k.extraCraters.seedXor)) {
    problems.push(`${k.id}: extraCraters.seedXor required`);
  }
  for (const id of k.landforms || []) {
    if (!formIds.has(id)) problems.push(`${k.id}: unknown landform "${id}"`);
  }
  for (const op of k.ops || []) {
    if (!op?.type) problems.push(`${k.id}: op missing type`);
    else if (allowedOps.size && !allowedOps.has(op.type)) {
      problems.push(`${k.id}: unknown op "${op.type}"`);
    }
    if (op.form && !formIds.has(op.form)) {
      problems.push(`${k.id}: op form "${op.form}" not in landforms.json`);
    }
  }
  if (k.base && !ids.has(k.base) && !kinds.some((x) => x.id === k.base)) {
    // may be forward-ref; check after loop
  }
}

for (const k of kinds) {
  if (k.base && !ids.has(k.base)) problems.push(`${k.id}: base "${k.base}" not found`);
}

if (!(src.version >= 2)) problems.push('stamps: version must be ≥ 2 (ops schema)');

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const L = [];
L.push('/** GENERATED by scripts/stamps.mjs from vr/data/worlds/stamps.json — do not edit. */');
L.push('');
L.push(`export const STAMP_VERSION = ${src.version | 0 || 1};`);
L.push(`export const STAMPS = Object.freeze(${JSON.stringify(kinds)}.map((k) => Object.freeze(k)));`);
L.push('export const STAMP_BY_ID = Object.freeze(Object.fromEntries(STAMPS.map((k) => [k.id, k])));');
L.push('');

await writeFile(OUT, L.join('\n'));
const nOps = kinds.reduce((n, k) => n + (k.ops?.length || 0), 0);
console.log(`stamps: ${kinds.length} kinds, ${nOps} ops -> vr/sim/stampTable.js`);
