#!/usr/bin/env node
// Compiles vr/data/worlds/substrates.json into vr/sim/substrates.js.
//
//   node scripts/substrates.mjs
//
// The JSON is the source of truth. This script validates it — unique ids,
// Earth rocks in slots 0–7, triple points on ices, provenance tags — and
// emits a frozen module so the browser needs no fetch.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'worlds', 'substrates.json');
const OUT = join(ROOT, 'vr', 'sim', 'substrates.js');

const EARTH_ROCKS = [
  'basalt', 'granite', 'sediment', 'metamorphic',
  'bandedIron', 'impactEjecta', 'coalMeasure', 'glacialTill',
];
const TAGS = new Set(['measured', 'fitted', 'invented']);
const CLASSES = new Set(['rock', 'ice', 'organics', 'salt', 'metal', 'fluid', 'envelope']);
const NUM = [
  'density', 'albedo', 'k', 'strength', 'erode',
  'meltK', 'boilK', 'tripleK', 'tripleBar', 'criticalK', 'criticalBar',
  'LsubJmol', 'convectK', 'thermalInertia', 'porosity',
];

const src = JSON.parse(await readFile(SRC, 'utf8'));
const materials = src.materials || [];
const problems = [];

if (!Array.isArray(materials) || materials.length < 16) {
  problems.push(`need at least 16 materials, got ${materials.length}`);
}

const ids = new Set();
for (let i = 0; i < materials.length; i++) {
  const m = materials[i];
  if (!m?.id || typeof m.id !== 'string') problems.push(`slot ${i}: missing id`);
  else if (ids.has(m.id)) problems.push(`duplicate id "${m.id}"`);
  else ids.add(m.id);
  if (!m?.name) problems.push(`${m?.id || i}: missing name`);
  if (!CLASSES.has(m?.class)) problems.push(`${m?.id || i}: class "${m?.class}" not in ${[...CLASSES].join('/')}`);
  if (!TAGS.has(m?.tag)) problems.push(`${m?.id || i}: tag "${m?.tag}" not measured/fitted/invented`);
  if (!m?.why || m.why.length < 20) problems.push(`${m?.id || i}: why must be a real sentence`);
  if (!Array.isArray(m?.rgb) || m.rgb.length !== 3
    || m.rgb.some((c) => !Number.isInteger(c) || c < 0 || c > 255)) {
    problems.push(`${m?.id || i}: rgb must be three integers 0–255`);
  }
  for (const k of ['density', 'albedo', 'k', 'strength', 'erode']) {
    if (!(typeof m?.[k] === 'number' && Number.isFinite(m[k]))) {
      problems.push(`${m?.id || i}: ${k} must be a finite number`);
    }
  }
  if (!(m.density > 0)) problems.push(`${m?.id || i}: density must be > 0`);
  if (m.albedo < 0 || m.albedo > 1) problems.push(`${m?.id || i}: albedo must be 0–1`);
  if (m.erode < 0) problems.push(`${m?.id || i}: erode must be ≥ 0`);
  for (const k of NUM) {
    if (m[k] != null && !Number.isFinite(m[k])) problems.push(`${m?.id || i}: ${k} is not finite`);
  }
  if (m.class === 'ice') {
    if (!(m.tripleK > 0) || !(m.tripleBar > 0)) {
      problems.push(`${m.id}: ices need tripleK and tripleBar`);
    }
    if (!m.cite || m.cite.length < 8) {
      problems.push(`${m.id}: ices need a cite (triple / vapour-pressure source)`);
    }
  }
  if (m.noSurface && m.id !== 'envelope') {
    problems.push(`${m.id}: noSurface is only for envelope`);
  }
  if (m.id === 'envelope' && !m.noSurface) {
    problems.push('envelope must set noSurface: true');
  }
}

for (let i = 0; i < EARTH_ROCKS.length; i++) {
  if (materials[i]?.id !== EARTH_ROCKS[i]) {
    problems.push(`slot ${i} must be ${EARTH_ROCKS[i]} (Earth ROCK_NAMES), got ${materials[i]?.id}`);
  }
}

for (const need of [
  'waterIce', 'co2Ice', 'n2Ice', 'ch4Ice', 'nh3Water', 'clathrate', 'tholin',
  'silicate', 'regolith', 'sulfur', 'evaporite', 'hydrocarbon', 'scCO2',
  'iron', 'graphite', 'envelope',
]) {
  if (!ids.has(need)) problems.push(`missing required material "${need}"`);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slim = materials.map((m) => {
  const o = {
    id: m.id, name: m.name, class: m.class,
    density: m.density, albedo: m.albedo, k: m.k,
    strength: m.strength, erode: m.erode, rgb: m.rgb,
    tag: m.tag, why: m.why,
  };
  for (const k of [
    'meltK', 'boilK', 'tripleK', 'tripleBar', 'criticalK', 'criticalBar',
    'LsubJmol', 'convectK', 'thermalInertia', 'porosity', 'soluble', 'noSurface',
    'cite',
  ]) {
    if (m[k] != null) o[k] = m[k];
  }
  return o;
});

const L = [];
L.push('/** GENERATED by scripts/substrates.mjs from vr/data/worlds/substrates.json — do not edit. */');
L.push('');
L.push(`export const SUBSTRATE_VERSION = ${src.version | 0 || 1};`);
L.push(`export const EARTH_ROCK_COUNT = ${EARTH_ROCKS.length};`);
L.push('');
L.push('/** Surface materials. Indices 0–7 match W.rock / ROCK_NAMES. */');
L.push(`export const SUBSTRATES = Object.freeze(${JSON.stringify(slim)}.map((m) => Object.freeze(m)));`);
L.push('');
L.push('export const SUB_BY_ID = Object.freeze(Object.fromEntries(SUBSTRATES.map((m) => [m.id, m])));');
L.push('export const SUB_INDEX = Object.freeze(Object.fromEntries(SUBSTRATES.map((m, i) => [m.id, i])));');
L.push('');
L.push('export function substrateAt(i) {');
L.push('  return SUBSTRATES[i] || SUBSTRATES[0];');
L.push('}');
L.push('');

await writeFile(OUT, L.join('\n') + '\n');
const nIce = slim.filter((m) => m.class === 'ice').length;
const nMeas = slim.filter((m) => m.tag === 'measured').length;
console.log(`substrates: ${slim.length} materials, ${nIce} ices, ${nMeas} measured`);
console.log('wrote vr/sim/substrates.js');
