#!/usr/bin/env node
// Compiles vr/data/techno/sources.json into vr/sim/technoTable.js.
//
//   node scripts/techno.mjs
//
// Energy sources are the source of truth. The compiler refuses unknown tags,
// a missing why, or a source without a power density.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'vr', 'data', 'techno', 'sources.json');
const OUT = join(ROOT, 'vr', 'sim', 'technoTable.js');

const TAGS = new Set(['measured', 'fitted', 'invented']);
const NEED = ['biomass', 'hydro', 'fossil', 'fission', 'fusion', 'orbital'];

const src = JSON.parse(await readFile(SRC, 'utf8'));
const sources = src.sources || [];
const problems = [];
const ids = new Set();

if (!(src.holoceneWatts > 0)) problems.push('holoceneWatts must be > 0');
if (!(src.earthAbsorbedW > 0)) problems.push('earthAbsorbedW must be > 0');
if (!(src.holoceneLandUse >= 0 && src.holoceneLandUse <= 1)) {
  problems.push('holoceneLandUse must be 0–1');
}

for (let i = 0; i < sources.length; i++) {
  const s = sources[i];
  const at = s?.id || `row ${i}`;
  if (!s?.id) problems.push(`source ${i}: missing id`);
  else if (ids.has(s.id)) problems.push(`duplicate source "${s.id}"`);
  else ids.add(s.id);
  if (!s?.name) problems.push(`${at}: missing name`);
  if (!TAGS.has(s?.tag)) problems.push(`${at}: tag "${s?.tag}"`);
  if (!s?.why || s.why.length < 20) problems.push(`${at}: why must be a sentence`);
  if (!(typeof s?.powerDensityWm2 === 'number' && s.powerDensityWm2 >= 0)) {
    problems.push(`${at}: powerDensityWm2 must be ≥ 0`);
  }
  if (!(typeof s?.co2KgPerJ === 'number' && s.co2KgPerJ >= 0)) {
    problems.push(`${at}: co2KgPerJ must be ≥ 0`);
  }
  if (!(typeof s?.landFootprint === 'number' && s.landFootprint >= 0)) {
    problems.push(`${at}: landFootprint must be ≥ 0`);
  }
}

for (const id of NEED) {
  if (!ids.has(id)) problems.push(`missing required source "${id}"`);
}

if (problems.length) {
  console.error(problems.map((p) => `  ${p}`).join('\n'));
  process.exit(1);
}

const slim = sources.map((s) => ({
  id: s.id,
  name: s.name,
  tag: s.tag,
  why: s.why,
  powerDensityWm2: s.powerDensityWm2,
  co2KgPerJ: s.co2KgPerJ,
  landFootprint: s.landFootprint,
  wasteHeatFrac: s.wasteHeatFrac ?? 1,
}));

const lines = [];
lines.push('/** GENERATED by scripts/techno.mjs from vr/data/techno/sources.json — do not edit. */');
lines.push('');
lines.push(`export const TECHNO_VERSION = ${src.version | 0 || 1};`);
lines.push(`export const EARTH_ABSORBED_W = ${src.earthAbsorbedW};`);
lines.push(`export const HOLOCENE_WATTS = ${src.holoceneWatts};`);
lines.push(`export const HOLOCENE_LAND_USE = ${src.holoceneLandUse};`);
lines.push(`export const WASTE_HEAT_ONSET = ${src.wasteHeatOnset};`);
lines.push(`export const POSTBIO_ONSET = ${src.postbioOnset};`);
lines.push('');
lines.push(`export const TECHNO_SOURCES = Object.freeze(${JSON.stringify(slim)}.map((k) => Object.freeze(k)));`);
lines.push('');
lines.push('export const SOURCE_BY_ID = Object.freeze(Object.fromEntries(');
lines.push('  TECHNO_SOURCES.map((k) => [k.id, k]),');
lines.push('));');
lines.push('');

await writeFile(OUT, `${lines.join('\n')}\n`);
console.log(`techno: ${sources.length} sources -> ${OUT}`);
