/** World field schema — quality-400 H1.
 *  Curated core of W; full census lives in vr/data/fields/ (H2).
 *  New field checklist: name, kind, type, unit?, owner, saved, derived.
 *  @provenance look
 */

/** @typedef {'field'|'scalar'|'record'|'flag'|'derived'|'meta'} FieldKind */

/**
 * @typedef {object} FieldRow
 * @property {string} name
 * @property {FieldKind} kind
 * @property {string} type  float32[] | uint8[] | number | object | …
 * @property {string} [unit]
 * @property {string} owner  module that may write — enforced when W.debugAssert === 'throw' (P21)
 * @property {string[]} [handoff]  ordered modules allowed to mutate (P24/P26); owner is primary
 * @property {boolean} saved
 * @property {boolean} [derived]
 * @property {string} [why]
 */

/**
 * G24 — structural type for curated W field names (checkJs / IDEs).
 * Not exhaustive of every runtime key; use fields census for the full set.
 * @typedef {object} WorldFieldsCore
 * @property {Float32Array} [h]
 * @property {Float32Array} [temp]
 * @property {Float32Array} [moist]
 * @property {Float32Array} [life]
 * @property {Float32Array} [clouds]
 * @property {number} [meanTemp]
 * @property {number} [meanLife]
 * @property {number} [seaLevel]
 * @property {number} [ageYr]
 */

/** Curated rows — source of truth for allocate / document / save planning. */
export const FIELDS = Object.freeze([
  {
    name: 'h',
    kind: 'field',
    type: 'float32[]',
    unit: 'relief',
    owner: 'tectonics',
    handoff: ['world', 'tectonics', 'earth', 'earthTerrain', 'god/sculpt', 'hydro'],
    saved: true,
    why: 'heightfield',
  },
  {
    name: 'temp',
    kind: 'field',
    type: 'float32[]',
    unit: 'mapT',
    owner: 'atmo',
    handoff: ['atmo', 'gpgpu', 'earth', 'god/climate', 'iceshell'],
    saved: false,
    why: 'surface temperature map',
  },
  {
    name: 'moist',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'hydro',
    handoff: ['hydro', 'earth', 'gpgpu', 'god/climate', 'god/brush'],
    saved: false,
  },
  {
    name: 'precip',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'hydro',
    handoff: ['hydro', 'weather'],
    saved: false,
  },
  { name: 'clouds', kind: 'field', type: 'float32[]', unit: '0-1', owner: 'atmo', saved: false },
  {
    name: 'ice',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'hydro',
    handoff: ['hydro', 'earth', 'iceshell', 'gpgpu', 'god/climate', 'god/sculpt'],
    saved: false,
  },
  { name: 'iceLand', kind: 'field', type: 'float32[]', unit: '0-1', owner: 'hydro', saved: false },
  { name: 'iceSea', kind: 'field', type: 'float32[]', unit: '0-1', owner: 'hydro', saved: false },
  {
    name: 'life',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'bio',
    handoff: ['bio', 'redox', 'fire', 'evolve', 'extinction', 'god/life', 'earth', 'weather'],
    saved: false,
    why: 'biomass density; bio owns modern Earth',
  },
  { name: 'fire', kind: 'field', type: 'float32[]', unit: '0-1', owner: 'fire', saved: false },
  {
    name: 'build',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'city',
    handoff: ['city', 'anthro', 'dark', 'weather'],
    saved: true,
  },
  { name: 'windU', kind: 'field', type: 'float32[]', unit: 'map', owner: 'wind', saved: false },
  { name: 'windV', kind: 'field', type: 'float32[]', unit: 'map', owner: 'wind', saved: false },
  { name: 'frost', kind: 'field', type: 'float32[]', unit: '0-1', owner: 'cover', saved: false },
  {
    name: 'ash',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'atmo',
    handoff: ['atmo', 'tectonics', 'fire', 'god/disaster', 'ordnance'],
    saved: false,
  },
  {
    name: 'crust',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'tectonics',
    saved: false,
  },
  { name: 'substrate', kind: 'field', type: 'uint8[]', owner: 'substrateField', saved: true },

  { name: 'meanTemp', kind: 'scalar', type: 'number', unit: 'mapT', owner: 'atmo', saved: false },
  { name: 'meanLife', kind: 'scalar', type: 'number', unit: '0-1', owner: 'bio', saved: false },
  { name: 'iceFrac', kind: 'scalar', type: 'number', unit: '0-1', owner: 'hydro', saved: false },
  { name: 'landFrac', kind: 'scalar', type: 'number', unit: '0-1', owner: 'hydro', saved: false },
  {
    name: 'seaLevel',
    kind: 'scalar',
    type: 'number',
    unit: 'relief',
    owner: 'hydro',
    handoff: ['hydro', 'earth', 'epoch', 'iceshell', 'god/sculpt'],
    saved: true,
  },
  { name: 'solar', kind: 'scalar', type: 'number', unit: 'S⊕', owner: 'atmo', saved: false },
  { name: 'year', kind: 'scalar', type: 'number', unit: 'a', owner: 'world', saved: true },
  { name: 'ageYr', kind: 'scalar', type: 'number', unit: 'a', owner: 'world', saved: true },
  { name: 'dtYr', kind: 'scalar', type: 'number', unit: 'a/tick', owner: 'world', saved: false },
  { name: 'seed', kind: 'meta', type: 'number', owner: 'world', saved: true },
  { name: 'health', kind: 'scalar', type: 'number', unit: '0-1', owner: 'gaia', saved: false },
  { name: 'resilience', kind: 'scalar', type: 'number', unit: '0-1', owner: 'gaia', saved: false },
  { name: 'energy', kind: 'scalar', type: 'number', owner: 'economy', saved: false },
  { name: 'waterDrift', kind: 'scalar', type: 'number', owner: 'assert', saved: false },

  {
    name: 'gases',
    kind: 'record',
    type: 'object',
    owner: 'atmo',
    handoff: ['atmo', 'carbon', 'epoch', 'god/climate'],
    saved: true,
  },
  { name: 'rule', kind: 'meta', type: 'object', owner: 'world', saved: true },
  { name: 'chron', kind: 'record', type: 'object', owner: 'chronicle', saved: true },
  { name: 'tree', kind: 'record', type: 'object', owner: 'evolve', saved: true },
  { name: 'transitions', kind: 'record', type: 'object', owner: 'redox', saved: true },
  { name: 'carbon', kind: 'record', type: 'object', owner: 'carbon', saved: false },
  {
    name: 'dark',
    kind: 'record',
    type: 'object',
    owner: 'dark',
    handoff: ['dark', 'world'],
    saved: true,
    why: 'optional ?dark=1 layer',
  },

  { name: 'autopilot', kind: 'flag', type: 'boolean', owner: 'gaiaDrive', saved: false },
  { name: 'gaiaDrive', kind: 'flag', type: 'string', owner: 'gaiaDrive', saved: false },
  { name: 'scarcityMode', kind: 'flag', type: 'string', owner: 'economy', saved: false },
  {
    name: '_atmScale',
    kind: 'derived',
    type: 'number',
    owner: 'cover',
    saved: false,
    derived: true,
  },
  {
    name: '_tropPole',
    kind: 'derived',
    type: 'number',
    owner: 'wind',
    saved: false,
    derived: true,
  },
  {
    name: '_degraded',
    kind: 'derived',
    type: 'string[]',
    owner: 'scheduler',
    saved: false,
    derived: true,
  },
  {
    name: '_waterMass0',
    kind: 'derived',
    type: 'number',
    owner: 'assert',
    saved: false,
    derived: true,
  },

  {
    name: 'bodies',
    kind: 'record',
    type: 'object',
    owner: 'sky',
    saved: true,
    why: 'lights + sats elements',
  },
  {
    name: 'sky',
    kind: 'record',
    type: 'object',
    owner: 'sky',
    saved: false,
    why: 'derived geometry per tick',
  },
  { name: 'spinPhase', kind: 'scalar', type: 'number', unit: 'rad', owner: 'sky', saved: true },
  { name: 'spinAxis', kind: 'scalar', type: 'number[]', unit: 'dir', owner: 'sky', saved: true },
  {
    name: 'precessionPhase',
    kind: 'scalar',
    type: 'number',
    unit: 'rad',
    owner: 'sky',
    saved: true,
  },
  { name: 'season', kind: 'scalar', type: 'number', unit: 'rad', owner: 'sky', saved: true },
  {
    name: 'obliquity',
    kind: 'scalar',
    type: 'number',
    unit: 'rad',
    owner: 'sky',
    handoff: ['god/climate', 'world'],
    saved: true,
  },
  {
    name: 'rotationPeriod',
    kind: 'scalar',
    type: 'number',
    unit: 'd⊕',
    owner: 'sky',
    handoff: ['god/climate', 'world', 'wind'],
    saved: true,
  },
  {
    name: 'moon',
    kind: 'record',
    type: 'object',
    owner: 'sky',
    handoff: ['god/climate', 'god/genesis'],
    saved: true,
    derived: true,
  },
  {
    name: '_moonDir',
    kind: 'derived',
    type: 'number[]',
    owner: 'sky',
    saved: false,
    derived: true,
  },
  { name: '_sunDir', kind: 'derived', type: 'number[]', owner: 'sky', saved: false, derived: true },
  /* Stacked, not planar: NC × AIR_LEVELS (8). Declared `derived` so the schema
     allocator in `world.js` leaves them alone — as `field` rows it sized them at
     NC and `allocAir` then threw those arrays away and allocated again. Same
     reason `colstack`'s `stackMat` / `stackM` are not schema rows. */
  {
    name: 'airT',
    kind: 'field',
    type: 'float32[]',
    unit: 'K',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'eight sigma levels of air temperature per cell',
  },
  {
    name: 'airQ',
    kind: 'field',
    type: 'float32[]',
    unit: 'kg/kg',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'eight sigma levels of specific humidity per cell',
  },
  {
    name: 'airU',
    kind: 'field',
    type: 'float32[]',
    unit: 'm/s',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'eight sigma levels of u-wind per cell (COL17)',
  },
  {
    name: 'airV',
    kind: 'field',
    type: 'float32[]',
    unit: 'm/s',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'eight sigma levels of v-wind per cell (COL17)',
  },
  {
    name: 'airZ',
    kind: 'field',
    type: 'float32[]',
    unit: 'm',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'geopotential height per level per cell (COL7)',
  },
  {
    name: 'cape',
    kind: 'field',
    type: 'float32[]',
    unit: 'J/kg',
    owner: 'aircol',
    handoff: ['aircol', 'weather'],
    saved: false,
    derived: true,
    why: 'convective available potential energy of a surface parcel',
  },
  {
    name: 'cin',
    kind: 'field',
    type: 'float32[]',
    unit: 'J/kg',
    owner: 'aircol',
    saved: false,
    derived: true,
  },
  {
    name: 'pwat',
    kind: 'field',
    type: 'float32[]',
    unit: 'mm',
    owner: 'aircol',
    saved: false,
    derived: true,
  },
  {
    name: 'lclKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
  },
  {
    name: 'srh',
    kind: 'field',
    type: 'float32[]',
    unit: 'm2/s2',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'storm-relative helicity, straight-hodograph closed form',
  },
  {
    name: 'ehi',
    kind: 'field',
    type: 'float32[]',
    unit: '1',
    owner: 'aircol',
    saved: false,
    derived: true,
  },
  {
    name: 'ascent',
    kind: 'field',
    type: 'float32[]',
    unit: '-1..1',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'mass-continuity vertical motion, positive up',
  },
  {
    name: 'tornadoRisk',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'aircol',
    saved: false,
    derived: true,
  },
  {
    name: 'mlDepthKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'mixed-layer depth (COL2)',
  },
  {
    name: 'freezeKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'height of 0°C isotherm (COL11)',
  },
  {
    name: 'elKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'equilibrium level — top of buoyant layer (COL13)',
  },
  {
    name: 'mlCape',
    kind: 'field',
    type: 'float32[]',
    unit: 'J/kg',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'mixed-layer CAPE (COL3)',
  },
  {
    name: 'sbCape',
    kind: 'field',
    type: 'float32[]',
    unit: 'J/kg',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'surface-based CAPE (COL3)',
  },
  {
    name: 'muCape',
    kind: 'field',
    type: 'float32[]',
    unit: 'J/kg',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'most-unstable CAPE from lowest 3 levels (COL4)',
  },
  {
    name: 'tropKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'lapse-rate tropopause height (COL8)',
  },
  {
    name: 'capK',
    kind: 'field',
    type: 'float32[]',
    unit: 'K',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'cap inversion strength — warming with height in low levels (COL10)',
  },
  {
    name: 'wbzKm',
    kind: 'field',
    type: 'float32[]',
    unit: 'km',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'wet-bulb zero height (COL12)',
  },
  {
    name: 'gust',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
  },
  {
    name: 'convRain',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'convective rain fraction, ephemeral — recomputed each tick from CAPE and pwat',
  },
  {
    name: 'drought',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: true,
    why: 'slow accumulator — the only weather state with memory worth saving',
  },
  {
    name: 'precipNorm',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'slow rainfall normal — what a drought is anomalous against',
  },
  {
    name: 'air',
    kind: 'record',
    type: 'object',
    owner: 'aircol',
    saved: false,
    derived: true,
    why: 'column summary + stripe state; one record, not a dozen scalars (P14)',
  },
  {
    name: 'wx',
    kind: 'record',
    type: 'object',
    owner: 'weather',
    saved: false,
    why: 'severe markers, drought summary, controls',
  },
  {
    name: 'wxClock',
    kind: 'record',
    type: 'object',
    owner: 'weatherClock',
    saved: false,
    why: 'lived-time weather dial — hours-per-second, diurnal factor (COL21–30)',
  },

  {
    name: 'convClass',
    kind: 'field',
    type: 'uint8[]',
    unit: '0-5',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'organised convection class (CONV23/25)',
  },
  {
    name: 'convOrg',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'organisation index',
  },
  {
    name: 'coldPool',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'cold-pool outflow triggering lift at neighbours (CONV23)',
  },
  {
    name: 'stormMotionU',
    kind: 'field',
    type: 'float32[]',
    unit: 'map',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'Bunkers right-mover u (CONV32)',
  },
  {
    name: 'stormMotionV',
    kind: 'field',
    type: 'float32[]',
    unit: 'map',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'Bunkers right-mover v (CONV32)',
  },
  {
    name: 'virga',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'precip evaporated before reaching surface (CONV37)',
  },
  {
    name: 'precipConv',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'convective share of total precip (CONV6)',
  },
  {
    name: 'precipStrat',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'stratiform share of total precip (CONV6)',
  },
  {
    name: 'rainMmHr',
    kind: 'field',
    type: 'float32[]',
    unit: 'mm/h',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'rain rate scaled to mm/hr (CONV41)',
  },
  {
    name: 'floodRisk',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'convect',
    saved: false,
    derived: true,
    why: 'flash flood risk from precip+slope+soil (CONV43)',
  },
  {
    name: 'stp',
    kind: 'field',
    type: 'float32[]',
    unit: '1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'significant tornado parameter from CAPE, SRH, LCL, shear (SEV3)',
  },
  {
    name: 'shear01',
    kind: 'field',
    type: 'float32[]',
    unit: 'm/s',
    owner: 'weather',
    saved: false,
    derived: true,
    why: '0–1 km shear from airU/V (SEV4)',
  },
  {
    name: 'scar',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    why: 'storm damage scar, decays over time (SEV11)',
  },
  {
    name: 'severeOutlook',
    kind: 'field',
    type: 'float32[]',
    unit: '0-5',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'convective outlook category 0–5 from ingredients (SEV39)',
  },
  {
    name: 'sstWake',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'storms',
    saved: false,
    why: 'cold wake SST depression behind storms (CYC7)',
  },
  {
    name: 'stormCone',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'storms',
    saved: false,
    derived: true,
    why: 'forecast cone uncertainty cells ahead of storms (CYC)',
  },
  {
    name: 'shelter',
    kind: 'scalar',
    type: 'number',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    why: 'agent shelter scalar when severe weather is nearby (SEV41)',
  },
  {
    name: 'disasterMem',
    kind: 'scalar',
    type: 'number',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    why: 'disaster memory decaying accumulator (SEV41)',
  },

  /* ── FRONT fields ────────────────────────────────────────── */
  {
    name: 'frontStrength',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'frontogenesis intensity (FRONT1)',
  },
  {
    name: 'frontKind',
    kind: 'field',
    type: 'uint8[]',
    unit: '0-4',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'cold/warm/occluded/stationary (FRONT2–5)',
  },
  {
    name: 'windShift',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'cross-front velocity change (FRONT8)',
  },
  {
    name: 'dryline',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'moisture jump without T jump (FRONT11)',
  },
  {
    name: 'stormTrack',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    why: 'accumulated cyclone / front activity (FRONT13)',
  },
  {
    name: 'eady',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'Eady-like baroclinic growth rate (FRONT14)',
  },
  {
    name: 'block',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    why: 'blocking high persistence (FRONT20)',
  },
  {
    name: 'coldTongue',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'fronts',
    saved: false,
    derived: true,
    why: 'cold outbreak tongue (FRONT25)',
  },

  /* ── DRY fields ──────────────────────────────────────────── */
  {
    name: 'soilRoot',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    why: 'root-zone soil moisture (DRY1)',
  },
  {
    name: 'soilDeep',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    why: 'deep soil moisture store (DRY2)',
  },
  {
    name: 'aridity',
    kind: 'field',
    type: 'float32[]',
    unit: '0-5',
    owner: 'weather',
    saved: false,
    why: 'PET/precipClimo — climate aridity (DRY6)',
  },
  {
    name: 'droughtClass',
    kind: 'field',
    type: 'uint8[]',
    unit: '0-4',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'drought severity class (DRY8)',
  },
  {
    name: 'droughtAge',
    kind: 'field',
    type: 'float32[]',
    unit: 'ticks',
    owner: 'weather',
    saved: false,
    why: 'drought duration counter (DRY10)',
  },
  {
    name: 'droughtRegion',
    kind: 'field',
    type: 'int32[]',
    unit: 'id',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'drought region label (DRY9)',
  },
  {
    name: 'heatIndex',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'heatwave index from block + temp (DRY13)',
  },
  {
    name: 'flashDrought',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'rapid soilRoot drop (DRY17)',
  },
  {
    name: 'petField',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'potential evapotranspiration (DRY4)',
  },
  {
    name: 'aetField',
    kind: 'field',
    type: 'float32[]',
    unit: '0-1',
    owner: 'weather',
    saved: false,
    derived: true,
    why: 'actual evapotranspiration (DRY5)',
  },
]);

export const FIELD_BY_NAME = Object.freeze(Object.fromEntries(FIELDS.map((r) => [r.name, r])));

export function fieldCount() {
  return FIELDS.length;
}

export function fieldsByKind(kind) {
  return FIELDS.filter((r) => r.kind === kind);
}

export function savedFields() {
  return FIELDS.filter((r) => r.saved);
}

/** Schema hash stub for saves (H37 / D37). */
export function fieldsSchemaHash() {
  let h = 0;
  for (const r of FIELDS) {
    const s = `${r.name}:${r.kind}:${r.saved ? 1 : 0}`;
    for (let i = 0; i < s.length; i++) h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}
