/** GENERATED by scripts/kindrules.mjs from vr/data/worlds/kindRules.json — do not edit. */

export const KIND_VERSION = 1;
export const KIND_NAMED = Object.freeze([{"kind":"earth","on":"ident","re":"\\bearth\\b","not":"super"},{"kind":"jupiter","on":"name","re":"\\bjupiter\\b"},{"kind":"saturn","on":"name","re":"\\bsaturn\\b","not":"rhea|dione|tethys|iapetus|mimas|enceladus|titan|hyperion"},{"kind":"uranus","on":"name","re":"\\buranus\\b","not":"miranda|ariel|umbriel|titania|oberon|uranian"},{"kind":"neptune","on":"name","re":"\\bneptune\\b","not":"triton"},{"kind":"io","on":"name","re":"\\bio\\b","not":"ion"},{"kind":"venus","on":"name","re":"venus"},{"kind":"mars","on":"name","re":"\\bmars\\b"},{"kind":"mercury","on":"name","re":"mercury"},{"kind":"moon","on":"name","re":"\\bluna\\b|\\bmoon\\b|selene"},{"kind":"enceladus","on":"name","re":"enceladus"},{"kind":"titan","on":"name","re":"\\btitan\\b"},{"kind":"pluto","on":"name","re":"\\bpluto\\b","not":"charon"},{"kind":"triton","on":"name","re":"triton"},{"kind":"ganymede","on":"name","re":"ganymede"},{"kind":"callisto","on":"name","re":"callisto"},{"kind":"europa","on":"name","re":"europa"},{"kind":"iapetus","on":"name","re":"iapetus"},{"kind":"miranda","on":"name","re":"miranda"},{"kind":"mimas","on":"name","re":"mimas"},{"kind":"charon","on":"name","re":"charon"},{"kind":"phobos","on":"name","re":"phobos|deimos"},{"kind":"ceres","on":"name","re":"ceres"},{"kind":"eris","on":"name","re":"eris|sedna"},{"kind":"smallbody","on":"name","re":"arrokoth|bennu|67p"},{"kind":"rhea","on":"name","re":"rhea|dione|tethys|hyperion"},{"kind":"uranian","on":"name","re":"ariel|umbriel|titania|oberon|uranian"}].map((k) => Object.freeze(k)));
export const GAS_KINDS = Object.freeze(new Set(["gas","jupiter","saturn","uranus","neptune"]));
export const WHITTAKER_KINDS = Object.freeze(new Set(["earth","daisy","generic"]));

let compiled = null;
function compile() {
  if (compiled) return compiled;
  compiled = KIND_NAMED.map((r) => ({
    kind: r.kind,
    on: r.on,
    re: new RegExp(r.re),
    not: r.not ? new RegExp(r.not) : null,
  }));
  return compiled;
}

/** First matching named kind, or null. */
export function matchNamedKind(name, ident) {
  for (const r of compile()) {
    const s = r.on === 'ident' ? ident : name;
    if (r.re.test(s) && (!r.not || !r.not.test(s))) return r.kind;
  }
  return null;
}
