/** GENERATED by scripts/techno.mjs from vr/data/techno/sources.json — do not edit. */

export const TECHNO_VERSION = 1;
export const EARTH_ABSORBED_W = 120000000000000000;
export const HOLOCENE_WATTS = 20000000000000;
export const HOLOCENE_LAND_USE = 0.5;
export const WASTE_HEAT_ONSET = 0.01;
export const POSTBIO_ONSET = 0.1;

export const TECHNO_SOURCES = Object.freeze([{"id":"biomass","name":"Biomass","tag":"measured","why":"Firewood and crop residue. Power density is a field, not a plant. Carbon is already in the fast cycle so this source does not unbury rock carbon.","powerDensityWm2":0.4,"co2KgPerJ":0,"landFootprint":1,"wasteHeatFrac":1},{"id":"hydro","name":"Hydro","tag":"measured","why":"Dams convert potential energy. Density is a reservoir plus a river, and the land cost is the drowned valley.","powerDensityWm2":3,"co2KgPerJ":0,"landFootprint":0.4,"wasteHeatFrac":1},{"id":"fossil","name":"Fossil","tag":"measured","why":"Coal, oil, gas. Oxidising buried organic carbon runs the carbon cycle backwards. Intensity is a coal-plant sketch, not a well-to-wake LCA.","powerDensityWm2":200,"co2KgPerJ":7e-8,"landFootprint":0.08,"wasteHeatFrac":1},{"id":"fission","name":"Fission","tag":"measured","why":"Thermal plants still dump heat. Land is the exclusion zone, not the fuel. No waste-heat exemption.","powerDensityWm2":50,"co2KgPerJ":0,"landFootprint":0.05,"wasteHeatFrac":1},{"id":"fusion","name":"Fusion","tag":"invented","why":"Engineering, not a measured source. Waste heat still equals input. Do not treat this as a claim that fusion exists on the planet.","powerDensityWm2":1000,"co2KgPerJ":0,"landFootprint":0.03,"wasteHeatFrac":1},{"id":"orbital","name":"Orbital solar","tag":"invented","why":"Collectors off-world still deliver watts that become heat at the surface, or beam them elsewhere. Speculation. Not a Dyson swarm.","powerDensityWm2":300,"co2KgPerJ":0,"landFootprint":0,"wasteHeatFrac":1}].map((k) => Object.freeze(k)));

export const SOURCE_BY_ID = Object.freeze(Object.fromEntries(
  TECHNO_SOURCES.map((k) => [k.id, k]),
));

